### PR TITLE
First pass at moving lassen to new adt

### PR DESCRIPTION
**Pull request by cdonovick**

### CODE REVIEW

**Comment by cdonovick** [comment]
Currently broken in the metamapper and the rtl gen

**Comment by leonardt** [comment]
RTL tests are failing with `peak/peak/auto_assembler.py:166: TypeError`. I think this is just because `peak.auto_assembler` hasn't been updated to use the new hwtypes adt?

**Comment by cdonovick** [comment]
@leonardt peak was using the wrong branch the auto_assembler should work

**Comment by leonardt** [comment]
Got it, seems like RTL is passing in the travis log. There was a bug in magma that was fixed today, so the issue might have been related to that? Are you still seeing an issue locally?

**Comment by cdonovick** [comment]
@rdaly525 whats the status of metamapper?

**Comment by rdaly525** [comment]
@leonardt, This is now failing on a one of the RTL tests. Could you take a look?

**Comment by leonardt** [comment]
Fixed some issues getting the dependencies installed. RTL (and all other) tests are now passing.

**Comment by Kuree** [comment]
What's the status of this? Can I use the mapper now or do I still have to wait?

**Pull request merged**
