### PR TITLE
Updates for magma 2

### PR DESCRIPTION
**Pull request by cdonovick**

### CODE REVIEW

**Comment by leonardt** [comment]
turns out masking the bottom bit isn't enough because rounding may cause more than one bit to flip (e.g. rounding `0x07` to `0x08`)

**Comment by leonardt** [comment]
Changed name of PR since we don't need the masking logic anymore, now it just inserts an extra `eval`/`#1` at the beginning of the test bench so the rounding mode simulation code is triggered.

(For future reference: this was required because the RTL simulation model for the floating point IP has a guard against the simulation time step, and won't execute rounding logic until the tilmestep is greater than 0, so we start the simulation off by advancing to the next time step by inserting an initial `eval` call)

**Comment by cdonovick** [comment]
Hmmm interesting good to know

**Comment by rdaly525** [comment]
I do not quite understand why that is the case, but glad you found it!

**Pull request merged**
