### PR TITLE
Mapper features

### PR DESCRIPTION
**Pull request by rdaly525**
Contains the following:
-This simplifies the mapper interface for garnet. This will add the custom rewrite rules during initialization of the mapper.

-Script for generating rewrite rules
-set of lassen specific rules for most of the arithmetic/bitwise/comp ops.

Also adds the 16 bit constant rewrite rule that was missing in garnet.

Still on the list:
-LUTs, 1 bit constant, const/reg packing

### CODE REVIEW

**Comment by Kuree** [comment]
Why `rules/all.json` is here? Shouldn't it be in lassen since lassen is responsible for generating it? In the future if lassen changes the spec, does that mean someone also has to update the rules here?

**Comment by rdaly525** [comment]
Yes, that is correct. I am currently not automatically generating the rules every merge to master. This is  going to happen in the future though and I want to unblock downstream tools for now.

**Comment by Kuree** [comment]
Uness `const` packing is working, you can't map any halide application through. If you really want to unblock the downstream tools, you can try to convert `const` and `reg` into PE tiles. Even pointwise uses one const.

**Comment by rdaly525** [comment]
@Kuree just to be clear 16-bit constants are mapped to PEs. This should work currently.

**Comment by Kuree** [comment]
This is not what I've seen here. If you look at the updates I made, the
instance type is still `const`.
https://travis-ci.com/StanfordAHA/garnet/builds/111460480

**Comment by rdaly525** [comment]
@Kuree  https://travis-ci.com/StanfordAHA/garnet/builds/111800478 I am not seeing that with these changes.

**Comment by rdaly525** [comment]
@Kuree, what is the issue here?
https://travis-ci.com/StanfordAHA/garnet/builds/111814061

**Comment by Kuree** [comment]
Usually means the input is empty. I was not aware that you've fixed the `const`. I will take a look at your change.

**Comment by Kuree** [comment]
@rdaly525 Done.

**Pull request merged**
