### PR TITLE
Added support for carry

### PR DESCRIPTION
**Pull request by rdaly525**
I just directly tied the output of the bit0 'register' to the carry in. This allows the ability to set a constant or a routable value to the carry while sacrificing one of the bit inputs.

I tested this using the complex op Add32

### CODE REVIEW

**Comment by phanrahan** [comment]
I was thinking we should add two new instructions, adc and sbc. Those instructions would connect bit0 to cin. The normal add and sub instructions would connect 0 or 1 to cin. The advantage of this design is that the LUT can be used independent of the adder.

**Comment by rdaly525** [comment]
I agree that it would be simpler from an isa point of view. It will add a little bit more circuitry though.

**Comment by rdaly525** [comment]
@phanrahan, could you re-review? I made the changes to use adc and sbc.

**Comment by rdaly525** [comment]
@phanrahan or @leonardt, could you review?

**Pull request merged**
