### PR TITLE
RTL (w/o float) works

### PR DESCRIPTION
**Pull request by leonardt**
Final changes to support RTL compilation for the lassen spec (modulo the new FP ops, working on support for that after integration with the encoder/decoder).

Depends on the changes from the RTL branch (which mainly refactors everything to the use generator pattern).

Requires the `lassen` branches of magma and mantle.

### CODE REVIEW

**Comment by rdaly525** [comment]
@leonardt, can you merge the travis branch into this PR and add the appropriate Magma/Mantle dependencies?

**Comment by rdaly525** [comment]
@alexcarsello, Do you want to take a look at these files before we merge?

**Comment by leonardt** [comment]
Mostly the second (need to add primitives to mantle and bfloat type to magma), however once that's done we'll need to make sure that they're written in a way that supports RTL generation, but I anticipate that any issues will be minor (e.g. small syntax changes like unrolling the for loop).

**Comment by leonardt** [comment]
re: Ross's comment on embedding RTL generation, right now we require explicit hooks in the user code so the magma logic can capture the closure environment for each definition (required for code generation). One way to do this would be capture the closure in the Peak class definition logic (using metaclasses), perhaps Python already provides access to the closure via the inspect environment. I think this is a minor frontend issue that should be resolved after we get the minimum working example with the encoder/decoder and float ops.

**Pull request merged**
