### PR TITLE
Fix pe bug

### PR DESCRIPTION
**Pull request by Kuree**

### CODE REVIEW

**Comment by rdaly525** [comment]
Can you add a small unit test for this?

**Comment by Kuree** [comment]
Sure. I doubt the small unit tests are going to help much though. The fact that there is a bug in the PE core and it's until the end-to-end test it's been found is very concerning.

**Comment by rdaly525** [comment]
Yes, Lassen needs a lot more unit tests.

**Comment by Kuree** [comment]
Also fixed `umin` instruction.

**Comment by Kuree** [comment]
Also fixed `umax`, `smin`, and `smax`

**Pull request merged**
